version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my_secure_password  # Set your own password here
      MYSQL_DATABASE: todo_app
    ports:
      - "3306:3306"
    volumes:
      - ./init/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my_secure_password  # Use the same password here
      - DB_NAME=todo_app
    ports:
      - "50054:50054"
    depends_on:
      db:
        condition: service_healthy
    command: ./todo-cli
